require(Yano)

obj.sm <- readRDS("object_sm.rds")
DefaultAssay(obj.sm) <- "RNA"
obj <- subset(obj.sm, subclass_label %in% c("L5 IT", "L6 IT"))

# Reload other assays to remove features expressed few than 20 cells
cells <- colnames(obj)

exon <- ReadPISA("Smartseq2/exon/")
junction <- ReadPISA("Smartseq2/junction/")
exclude <- ReadPISA("Smartseq2/exclude/")

obj[['exon']] <- CreateAssayObject(exon[,cells], min.cells = 20)
obj[['junction']] <- CreateAssayObject(junction[,cells], min.cells = 20)
obj[['exclude']] <- CreateAssayObject(exclude[,cells], min.cells = 20)

DefaultAssay(obj) <- "RNA"
obj <- ScaleData(obj, vars.to.regress = "nCount_RNA")
obj <- RunPCA(obj,verbose=FALSE) %>% FindNeighbors(dims = 1:20, verbose=FALSE) %>% FindClusters(resolution = 0.5, verbose=FALSE) %>% RunUMAP(dims=1:20, verbose=FALSE)
Idents(obj) <- obj$subclass_label

DefaultAssay(obj) <- 'exon'
obj <- NormalizeData(obj)
obj <- RunAutoCorr(obj)
obj <- SetAutoCorrFeatures(obj)
obj <- ParseExonName(obj)
obj <- RunBlockCorr(obj, bind.assay = "RNA")

DefaultAssay(obj) <- 'junction'
obj <- NormalizeData(obj)
obj <- RunAutoCorr(obj)
obj <- SetAutoCorrFeatures(obj)
obj <- ParseExonName(obj)
obj <- RunBlockCorr(obj, bind.assay = "RNA")

##########################################################################################################
##   Figure 3B, Run DEXSeq
##########################################################################################################
DefaultAssay(obj) <- "exon"
de <- RunDEXSeq(obj)
de0 <- subset(de, cluster == "L5 IT")
sel <- intersect(rownames(de0),AutoCorrFeatures(obj))
de0 <- de0[sel,]
p <- ggplot() + geom_point(data=de0, aes(log2fc, -log10(padj))) + theme_pubr() + xlab("") + ylab("")
ggsave(p, file = "DEXSeq.png", width =4, height = 3)

##########################################################################################################
##   Figure 3C
##########################################################################################################
obj[['exon']][[]] -> df

df <- df[sel,]
df$DEXSeq.padj <- de0$padj
p <- ggplot() + geom_point(data=df, aes(-log10(gene_name.padj), -log10(DEXSeq.padj))) + geom_point(data=df[c("chr12:40799657-40799750/Dock4", "chr15:74955071-74955717/Ly6e", "chr8:94870508-94873535/Polr2c", "chr5:142903234-142903400/Actb"),], aes(-log10(gene_name.padj), -log10(DEXSeq.padj)), color = "red", size=2) + geom_label_repel(data=df[c("chr12:40799657-40799750/Dock4", "chr15:74955071-74955717/Ly6e", "chr8:94870508-94873535/Polr2c", "chr5:142903234-142903400/Actb"),], aes(-log10(gene_name.padj), -log10(DEXSeq.padj), label = exon_name), nudge_y = c(20,20,100,30), nudge_x=10, size=3)
p <- p + theme_pubr() + xlab("") + ylab("")# + ggtitle("SDT vs DEXSeq")
ggsave(p, file = "fig03_3.png", width =4, height = 3)

##########################################################################################################
##   Figure 3D, 3E, 3F, 3G
##########################################################################################################

p1 <- FeaturePlot_scCustom(obj, features = c("chr15:74955071-74955717/Ly6e"), order = TRUE, pt.size=1, figure_plot = TRUE) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p2 <- FeaturePlot_scCustom(obj, features = c("Ly6e"), order = TRUE, pt.size=1, figure_plot=TRUE) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))

p3 <- FeaturePlot_scCustom(obj, features = c("chr12:40799657-40799750/Dock4"), order = TRUE, pt.size=1, figure_plot=TRUE) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p4 <- FeaturePlot_scCustom(obj, features = c("Dock4"), order = TRUE, pt.size=1, figure_plot=TRUE) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))

p5 <- FeaturePlot_scCustom(obj, features = c("chr8:94870508-94873535/Polr2c"), order = TRUE, pt.size=1, figure_plot=TRUE) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p6 <- FeaturePlot_scCustom(obj, features = c("Polr2c"), order = TRUE, pt.size=1, figure_plot=TRUE) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))

p7 <- FeaturePlot_scCustom(obj, features = c("chr5:142903234-142903400/Actb"), order = TRUE, pt.size=1, figure_plot=TRUE) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p8 <- FeaturePlot_scCustom(obj, features = c("Actb"), order = TRUE, pt.size=1, figure_plot=TRUE) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))

p <- cowplot::plot_grid(p1,p2,p3,p4, p5,p6,p7,p8, ncol=4)
ggsave(p, file = "fig03_D_G_features.pdf")

##########################################################################################################
##   Figure 3H
##########################################################################################################

## Read data generated by Brie2.sh
gene.notes <- as.data.frame(fread("./brie2/gene_note.tsv"))
rownames(gene.notes) <- gene.notes$GeneID
brie2 <- as.data.frame(fread("./brie2/brie_quant_cell_L5IT.brie_ident.tsv"))

brie2$GeneName <- gene.notes[brie2$GeneID,]$GeneName
p <- ggplot() + geom_point(data=brie2,aes(isL5_ceoff, isL5_ELBO_gain), color = "grey")
p <- p + geom_point(data=subset(brie2, isL5_ELBO_gain>10), aes(isL5_ceoff, isL5_ELBO_gain))
p <- p + geom_label_repel(data=subset(brie2, isL5_ELBO_gain>50), aes(isL5_ceoff, isL5_ELBO_gain, label = GeneName))
p <- p + theme_pubr() + xlab("") + ylab("")
ggsave(p, file = "brie2.png", width = 4, height = 4)

genes <- subset(brie2, isL5_ELBO_gain>30)$GeneName %>% unique


DefaultAssay(obj) <- "exon"
obj[['exon']][['exon_name']] <- rownames(obj)
obj <- RunBlockCorr(obj, bind.name = "exon_name", bind.assay = "exclude", mode = 3, prefix = "mode3")

DefaultAssay(obj) <- "exclude"
obj[['exclude']][['exon_name']] <- rownames(obj)
obj <- NormalizeData(obj)
obj <- RunAutoCorr(obj)
obj <- SetAutoCorrFeatures(obj)
obj <- ParseExonName(obj)
obj <- RunBlockCorr(obj, bind.name = "exon_name", bind.assay = "exon", mode = 3, prefix="mode3")

obj[['exon']][[]] %>% filter(mode3.padj<1e-10) %>% pull(gene_name) %>% unique -> sel1
obj[['exclude']][[]] %>% filter(mode3.padj<1e-10) %>% pull(gene_name) %>% unique -> sel2
length(unique(c(sel1,sel2)))

setdiff(genes,unique(c(sel1,sel2))) # five genes should be printed out

###################################################################################################
##   Figure 3I
###################################################################################################
p <- FbtPlot(obj, assay = c("exon", "exclude"), val = "mode3.padj", remove.chr = TRUE, sel.chrs = c(1:21,"X"), shape.by = "assay", col.by = "assay", pt.size=3, cols = c("grey40", "yellow"),label.size=8, point.label = c("chr3:80691320-80691434/Gria2")) + xlab("") + ylab("") + theme(legend.position = "none")
ggsave(p, file = "sm3_exon_junc_mode3.png", width = 15, height = 6)


###################################################################################################
##   Figure 3J, 3K
###################################################################################################

DefaultAssay(obj) <- "exon"
p1 <- FeaturePlot_scCustom(obj, features = "chr3:80691320-80691434/Gria2", figure_plot = TRUE, order = TRUE, pt.size=1) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p3 <- FeaturePlot_scCustom(obj, features = "chr16:7193747-7193877/Rbfox1", figure_plot = TRUE, order = TRUE, pt.size=1) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
DefaultAssay(obj) <- "exclude"
p2 <- FeaturePlot_scCustom(obj, features =  "chr3:80691320-80691434/Gria2", figure_plot = TRUE, order = TRUE, pt.size=1) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p4 <- FeaturePlot_scCustom(obj, features = "chr16:7193747-7193877/Rbfox1", figure_plot = TRUE, order = TRUE, pt.size=1) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p <- cowplot::plot_grid(p1,p2,p3,p4, ncol = 4)
ggsave(p, file = "brie2_features_1.pdf")


###################################################################################################
##   Figure 3L, 3M
###################################################################################################
DefaultAssay(obj) <- "exon"
p1 <- FeaturePlot_scCustom(obj, features = "chr13:6588955-6596062/Pfkp", figure_plot = TRUE, order = TRUE, pt.size=1) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p3 <- FeaturePlot_scCustom(obj, features = "chr18:38447713-38447821/Ndfip1", figure_plot = TRUE, order = TRUE, pt.size=1) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
DefaultAssay(obj) <- "exclude"
p2 <- FeaturePlot_scCustom(obj, features = "chr13:6588955-6596062/Pfkp", figure_plot = TRUE, order = TRUE, pt.size=1) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p4 <- FeaturePlot_scCustom(obj, features = "chr18:38447713-38447821/Ndfip1", figure_plot = TRUE, order = TRUE, pt.size=1) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
p <- cowplot::plot_grid(p1,p2,p3,p4, ncol = 4)
ggsave(p, file = "brie2_features_2.pdf")

saveRDS(obj, file = "object_sm1.rds")
